EXP_ID: &EXP_ID voc12
TEST_ID:  CRF_NO_AUG_UPSAMPLE_LOGIT

DATASET:
    NAME: voc
    ROOT: ./data/datasets
    # LABELS: ./data/datasets/voc12/labels.txt
    N_CLASSES: 21
    IGNORE_LABEL: 255
    SCALES: [0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0]
    SPLIT:
        TRAIN: train
        VAL: val
        TEST: test

DATALOADER:
    NUM_WORKERS: 8

IMAGE:
    MEAN:
        R: 122.675
        G: 116.669
        B: 104.008
    SIZE:
        BASE: # None
        TRAIN: 321
        TEST: 321

MODEL:
    NET_ID: pascal
    TEST_AT: "final"
    MSC_FACTORS: [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]

SOLVER:
    BATCH_SIZE:
        TEST: 1

CRF:
    IS_CRF: true
    ITER_MAX: 10
    POS_W: 3
    POS_XY_STD: 2
    BI_W: 4
    BI_XY_STD: 65
    BI_RGB_STD: 3
